[master]
localhost ansible_connection=local

[workstations]
hcfedclient.tuo_dominio.qualcosa ansible_host=ip_statico_host ansible_user=hcfedclient

[containers]
monitor-container ansible_connection=lxd ansible_user=root ansible_remote_tmp=/tmp
# Se hai sottomano il nome esatto del container Nginx creato nella Fase 5, inseriscilo qui sotto.
# Ad esempio:
# web-server-aziendale ansible_connection=lxd ansible_user=root