[all:vars]
# Definiamo l'utente SSH predefinito e i privilegi globali per il laboratorio
ansible_user=root
ansible_connection=ssh

[control_node]
# La torre di controllo stessa (collegamento locale)
ansible-control ansible_host=127.0.0.1 ansible_connection=local

[firewall]
# Qui inseriremo l'IP della Virtual Appliance perimetrale (pfSense / OPNsense)
# firewall01 ansible_host=x.x.x.X

[identity_servers]
# Qui inseriremo il futuro Domain Controller FreeIPA su Rocky Linux 9
hcrocky.hcro04.lan ansible_host=x.x.1.2 ansible_user=root
# dc01.hcprx01.lan ansible_host=x.x.x.X

[microservices]
# Spazio per i futuri container LXC (Gitea, Vaultwarden, Keycloak)

[management]
x.x.1.7 ansible_user=root