# 1. CANALE IN CHIARO (PORTA 80)
<VirtualHost *:80>
    ServerName intranet.hcro03.lan

    # Inoltra le richieste standard e i rinnovi futuri al container
    ProxyPass / http://10.216.247.75/
    ProxyPassReverse / http://10.216.247.75/
</VirtualHost>

# 2. CANALE CRITTOGRAFATO (PORTA 443)
<VirtualHost *:443>
    ServerName intranet.hcro03.lan

    # Attivazione SSL sull'Host Rocky verso l'utente esterno
    SSLEngine on
    SSLCertificateFile /etc/httpd/conf.d/intranet_fullchain.pem
    SSLCertificateKeyFile /etc/httpd/conf.d/intranet_privkey.pem

    # Abilita il motore proxy crittografato verso il retrobottega (container)
    SSLProxyEngine on
    
    # Disabilita i controlli stringenti sul certificato interno (andiamo via IP)
    SSLProxyVerify none
    SSLProxyCheckPeerCN off
    SSLProxyCheckPeerName off
    SSLProxyCheckPeerExpire off

    # Inoltra il traffico HTTPS sicuro al Nginx del container
    ProxyPass / https://10.216.247.75/
    ProxyPassReverse / https://10.216.247.75/
</VirtualHost>
