# 1. CANALE IN CHIARO (Rinnovi ACME)
<VirtualHost *:80>
    ServerName monitor.hcro03.lan

    ProxyPreserveHost On
    # Inoltra le sfide di rinnovo SSL a Certbot (standalone)
    ProxyPass / http://10.216.247.49:80/
    ProxyPassReverse / http://10.216.247.49:80/
</VirtualHost>

# 2. CANALE CRITTOGRAFATO (Grafana Dashboard)
<VirtualHost *:443>
    ServerName monitor.hcro03.lan

    # Attivazione SSL sull'Host Rocky
    SSLEngine on
    SSLCertificateFile /etc/httpd/conf.d/monitor_fullchain.pem
    SSLCertificateKeyFile /etc/httpd/conf.d/monitor_privkey.pem

    ProxyPreserveHost On
    # Inoltra il traffico HTTPS alla porta nativa di Grafana (3000)
    ProxyPass / http://10.216.247.49:3000/
    ProxyPassReverse / http://10.216.247.49:3000/
</VirtualHost>
