{
 "title": "Monitoraggio PC fisico e VM Debian",
 "description": "General stats dashboard with node selector, uses metrics from windows_exporter",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up{job=\"$job\"}, instance)"
    }
   },
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "hostname",
    "label": "hostname",
    "query": {
     "query": "label_values(up{job=\"$job\"}, hostname)"
    }
   },
   {
    "name": "show_hostname",
    "label": "show_hostname",
    "query": {
     "query": "label_values(windows_cs_hostname{job=~\"$job\",instance=~\"$instance\"}, hostname)"
    }
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "server",
    "label": "server",
    "query": {
     "query": "label_values(windows_system_system_up_time, instance)"
    }
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Log API (Puliti)",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{container=\"hc0-api\"} != \"/status\" != \"/favicon.ico\""
    }
   ]
  },
  {
   "title": "Temperatura CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_thermalzone_temperature_celsius{name=~\".*CPUZ.*\"} ",
     "legendFormat": "Temperatura CPU"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "windows_os_info{job=~\"$job\"} * on(instance) group_right(product) windows_cs_hostname"
    },
    {
     "expr": "time() - windows_system_system_up_time{job=~\"$job\"}"
    },
    {
     "expr": "windows_cs_logical_processors{job=~\"$job\"} - 0"
    },
    {
     "expr": "avg by (instance) (windows_cpu_core_frequency_mhz{job=~\"$job\"})"
    },
    {
     "expr": "100 - (avg by (instance) (irate(windows_cpu_time_total{job=~\"$job\",mode=\"idle\"}[2m])) * 100)",
     "legendFormat": "CPU test8"
    },
    {
     "expr": "windows_cs_physical_memory_bytes{job=~\"$job\"} - 0"
    },
    {
     "expr": "100 - 100 * windows_os_physical_memory_free_bytes{job=~\"$job\"} / windows_cs_physical_memory_bytes{job=~\"$job\"}",
     "legendFormat": "test8"
    },
    {
     "expr": "1 - (windows_logical_disk_free_bytes{job=~\"$job\",volume=~\"C:\"}/windows_logical_disk_size_bytes{job=~\"$job\",volume=~\"C:\"})"
    },
    {
     "expr": "max by (instance) (1-windows_logical_disk_free_bytes{job=~\"$job\"}/windows_logical_disk_size_bytes{job=~\"$job\"})"
    },
    {
     "expr": "windows_os_processes{job=~\"$job\"}"
    },
    {
     "expr": "sum by (instance) (windows_service_state{job=~\"$job\",state=~\"running\"})"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum by (mode) (rate(windows_cpu_time_total{instance=~\"$instance\"}[5m]))",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{mode}} ",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Windows OS Processes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "windows_system_processes", "legendFormat": "{{ instance }}" }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_memory_physical_total_bytes{instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Totale RAM",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_memory_available_bytes{instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "RAM usata",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "windows_memory_physical_total_bytes{instance=~\"$instance\"} - windows_memory_available_bytes{instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "RAM disponibile",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Hard drive load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_write_bytes_total{instance=~\"$instance\", volume !~\"HarddiskVolume.+\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Write {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "irate(windows_logical_disk_read_bytes_total{instance=~\"$instance\", volume !~\"HarddiskVolume.+\"}[5m])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Read {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Hard disk free space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_logical_disk_free_bytes{instance=~\"$instance\", volume !~\"HarddiskVolume.+\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "free {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Network discarded/error packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_net_packets_outbound_discarded_total{instance=~\"$instance\"}[$__rate_interval]) + rate(windows_net_packets_outbound_errors_total{instance=~\"$instance\"}[$__rate_interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{nic}} - Outbound",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "rate(windows_net_packets_received_discarded_total{instance=~\"$instance\"}[$__rate_interval]) + rate(windows_net_packets_received_errors_total{instance=~\"$instance\"}[$__rate_interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{nic}} - Inbound",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_net_bytes_sent_total{instance=~\"$instance\"}[5m]) >0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Sent {{nic}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "" },
     "expr": "- rate(windows_net_bytes_received_total{instance=~\"$instance\"}[5m]) <0",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Received {{nic}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Windows net byte  and bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(windows_net_bytes_received_total{instance=~\"$instance\", nic=~\"Realtek.*\"}[$__rate_interval])",
     "legendFormat": "{{nic}} - Download"
    },
    {
     "expr": "rate(windows_net_bytes_sent_total{instance=~\"$instance\", nic=~\"Realtek.*\"}[$__rate_interval])",
     "legendFormat": "{{nic}} - Upload"
    }
   ]
  },
  {
   "title": "Hard disk i/o ops total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "rate(windows_logical_disk_reads_total{instance=~\"$instance\", volume=\"C:\"}[$__rate_interval]) \r\n+ \r\nrate(windows_logical_disk_writes_total{instance=~\"$instance\", volume=\"C:\"}[$__rate_interval])",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "i/o {{volume}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(windows_cpu_time_total{instance=~\"$instance\", mode=\"idle\"}[$__rate_interval])) * 100)",
     "legendFormat": "CPU"
    }
   ]
  },
  { "title": "System Thread", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Attività Multi-threading",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "windows_system_threads{instance=~\"$instance\"}",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "system_threads",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Carico di Lavoro",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "windows_system_threads{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Errori Software",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(windows_system_exception_dispatches_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "exceptions"
    }
   ]
  },
  {
   "title": "Multitasking Overhead",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(windows_system_context_switches_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Chiamate di Sistema",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(windows_system_system_calls_total{instance=~\"$instance\"}[$__rate_interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Miscellenous", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Ultimo Riavvio",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocal" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_system_boot_time_timestamp{instance=~\"$instance\"} * 1000",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Servizi: In esecuzione vs Fermi",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(windows_service_state{instance=~\"$instance\"}) by (state)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{state}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Elenco Servizi Attivi",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(windows_service_info{instance=~\"$instance\"}) by (display_name)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{display_name}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Metodi di Avvio (Auto/Manuale)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 108 },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(windows_service_start_mode{instance=~\"$instance\"}) by (start_mode)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{start_mode}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Utilizzo Spazio di Archiviazione",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 108 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (windows_logical_disk_free_bytes{instance=~\"$instance\", volume=~\"[A-Z]:\"} / windows_logical_disk_size_bytes{instance=~\"$instance\", volume=~\"[A-Z]:\"}) * 100",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Salute dei Moduli di Raccolta",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 118 },
   "targets": [
    {
     "expr": "windows_exporter_collector_success{instance=~\"$instance\"}",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "Timeout Moduli",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 128 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "windows_exporter_collector_timeout{instance=~\"$instance\"}",
     "legendFormat": "{{collector}}"
    }
   ]
  }
 ]
}