services:
  db:
    image: postgres:alpine
    container_name: nextcloud_db
    restart: always
    volumes:
      - /srv/nextcloud-data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: <INSERIRE_PASSWORD_DB>
    networks:
      - nc_internal

  app:
    image: nextcloud:stable
    container_name: nextcloud_app
    restart: always
    depends_on:
      - db
    volumes:
      - /srv/nextcloud-data/app:/var/www/html
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: nextcloud
      POSTGRES_USER: nextcloud
      POSTGRES_PASSWORD: <INSERIRE_PASSWORD_DB>
      NEXTCLOUD_TRUSTED_DOMAINS: p0-lab-lin-nc01.lab.internal 10.250.250.108
    networks:
      - nc_internal

  web:
    image: nginx:alpine
    container_name: nextcloud_proxy
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /srv/nextcloud-data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
    networks:
      - nc_internal

networks:
  nc_internal:
    driver: bridge