#!/usr/sbin/nft -f

flush ruleset

table inet filter {
    chain input {
        type filter hook input priority 0; policy drop;

        # Loopback e connessioni stabilite
        iifname "lo" accept
        ct state established,related accept

        # ICMP (ping) e SSH amministrativo
        ip protocol icmp accept
        tcp dport 22 accept

        # Traffico applicativo IA (Accessibile dalla rete autorizzata)
        ip daddr 10.250.250.104 tcp dport 3000 accept
        ip daddr 10.250.250.104 tcp dport 11434 accept

        # Monitoraggio Zabbix Agent 2 limitato al solo server di monitoraggio
        ip saddr 10.250.250.135 tcp dport 10050 accept
    }

    chain forward {
        type filter hook forward priority 0; policy accept;
    }

    chain output {
        type filter hook output priority 0; policy accept;
    }
}

table ip nat {
    chain postrouting {
        type nat hook postrouting priority 100; policy accept;
        # Masquerade per il routing in uscita dei container Docker
        ip saddr 172.16.0.0/12 masquerade
    }
}