# Tuning del Kernel Linux per il Core Router (Alpine LXC)
# Abilitazione dell'IP Forwarding per il routing inter-VLAN
net.ipv4.ip_forward=1

# Configurazione del Data Plane MPLS (Label Switching)
net.mpls.platform_labels=100000
net.mpls.conf.eth0.input=1
net.mpls.conf.lo.input=1