apiVersion: v1
kind: Pod
metadata:
  name: app-stack
  labels:
    app: wordpress-enterprise
spec:
  nodeSelector:
    kubernetes.io/hostname: hcdebk3s
  containers:
    - name: db
      image: docker.io/library/mariadb:10.11
      env:
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_PASSWORD
          value: secret_password_nat64
        - name: MYSQL_ROOT_PASSWORD
          value: root_secret_password_nat64
      volumeMounts:
        - name: db-data
          mountPath: /var/lib/mysql

    - name: web
      image: docker.io/library/wordpress:latest
      ports:
        - containerPort: 80
      volumeMounts:
        - name: wp-data
          mountPath: /var/www/html
      env:
        - name: WORDPRESS_DB_HOST
          value: 127.0.0.1:3306
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          value: secret_password_nat64
        - name: WORDPRESS_DB_NAME
          value: wordpress
        - name: WORDPRESS_CONFIG_EXTRA
          value: |
            define('WP_HOME', 'http://app.azienda.lab');
            define('WP_SITEURL', 'http://app.azienda.lab');

  volumes:
    - name: db-data
      hostPath:
        path: /home/hcdebk3s/app-stack/db-data
        type: DirectoryOrCreate
    - name: wp-data
      hostPath:
        path: /home/hcdebk3s/app-stack/wp-data
        type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: app-stack-service
spec:
  type: NodePort
  selector:
    app: wordpress-enterprise
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30082